version: "3"
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 7002:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
